name: community_material_icon
description: A community material design icon
version: 2.8.94
author: rio permana <rio.prmn@gmail.com>
homepage: https://github.com/ripsware/community_material_icon

environment:
  sdk: '>=1.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: MaterialDesignIconFont
      fonts:
        - asset: packages/community_material_icon/fonts/materialdesignicons-webfont.ttf
